stages:
  - build
  - test

build_job:
  stage: build
  tags:
    - dotnet-2.1
  script: dotnet build

test_job:
  stage: test
  tags:
    - dotnet-2.1
  script:
    - cd HelloTest
    - dotnet test

sonarqube_job:
  stage: test
  tags:
    - dotnet-2.1
  script:
    - dotnet tool install --global dotnet-sonarscanner
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet sonarscanner begin /k:Hello /d:sonar.host.url=https://sonarqube.npsdev.cloud /d:sonar.login=6c1be6d8c1eb50867389313d3ea0c26dd6c0eb5c /d:sonar.analysis.mode=preview /d:sonar.gitlab.json_mode=CODECLIMATE /d:sonar.gitlab.failure_notification_mode=commit-status

