stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  image: microsoft/dotnet:2.1-sdk
  script: dotnet build

test:
  stage: test
  tags:
    - docker
  image: chaeyk/sonarscanner-netcore:2.1-sdk
  script:
    - dotnet sonarscanner begin /k:Hello /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONAR_USER_CHAEYK /d:sonar.sourceEncoding=UTF-8 /d:sonar.cs.opencover.reportsPaths="./coverage.xml"
    - dotnet build
    - cd tools
    - dotnet restore
    - dotnet minicover instrument --workdir ../ --assemblies **/bin/**/*.dll
    - dotnet minicover reset
    - cd ..
    - dotnet test --no-build HelloTest/HelloTest.csproj
    - cd tools
    - dotnet minicover uninstrument --workdir ../
    - dotnet minicover report --workdir ../ --threshold 0
    - dotnet minicover opencoverreport --workdir ../ --threshold 0 --output "./coverage.xml"
    - cd ..
    - dotnet sonarscanner end /d:sonar.login=$SONAR_USER_CHAEYK

