stages:
  - build
  - test

build_job:
  stage: build
  tags:
    - docker
  image: microsoft/dotnet:2.1-sdk
  script: dotnet build

test_job:
  stage: test
  tags:
    - docker
  image: microsoft/dotnet:2.1-sdk
  script:
    - cd HelloTest
    - dotnet test

sonarqube_job:
  stage: test
  tags:
    - docker
  image: chaeyk/sonarscanner-netcore:2.1-sdk
  script:
    - dotnet sonarscanner begin /k:Hello /d:sonar.host.url=$SONAR_HOST /d:sonar.login=$SONAR_USER_CHAEYK
    - dotnet build
    - dotnet sonarscanner end /d:sonar.login=$SONAR_USER_CHAEYK

