stages:
  - build
  - test

build_job:
  stage: build
  tags:
    - dotnet-2.1
  script: dotnet build

test_job:
  stage: test
  tags:
    - dotnet-2.1
  script:
    - cd HelloTest
    - dotnet test

